Controllers/GalleryCarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcBlog.Models;
using MvcBlog.ViewModel;

namespace MvcBlog.Controllers
{
    [ValidateInput(false)]
    public class GalleryCarsController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        

        // GET: GalleryCars
        public ActionResult Index()
        {
            var cars = db.GalleryCars.Include(g => g.Id);
            var carLinks = db.GalleryCars.Include(g =>g.Id);
            this.ViewBag.CarLinks = carLinks;
            return View(db.GalleryCars.ToList());
        }

        // GET: GalleryCars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GalleryCar galleryCar = db.GalleryCars.Find(id);
            if (galleryCar == null)
            {
                return HttpNotFound();
            }
            var myViewModel = new GalleryCarViewModel();
            var lastItem = db.GalleryCars.OrderByDescending(x => x.Id).First();
            var firstItem = db.GalleryCars.OrderBy(x => x.Id).First();
            var carComments = db.Comments.Where(c => c.Post.Id == galleryCar.Id).Include(c => c.Author).ToList();
            myViewModel.lastItemID = lastItem.Id;
            myViewModel.firstItemID = firstItem.Id;
            myViewModel.Car = galleryCar;
            myViewModel.carComments = carComments;
            return View(myViewModel);
        }

        // GET: GalleryCars/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GalleryCars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,URL,Description")] GalleryCar galleryCar)
        {
            if (ModelState.IsValid)
            {
                db.GalleryCars.Add(galleryCar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(galleryCar);
        }

        // GET: GalleryCars/Edit/5
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GalleryCar galleryCar = db.GalleryCars.Find(id);
            if (galleryCar == null)
            {
                return HttpNotFound();
            }
            return View(galleryCar);
        }

        // POST: GalleryCars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,URL,Description")] GalleryCar galleryCar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(galleryCar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(galleryCar);
        }

        // GET: GalleryCars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GalleryCar galleryCar = db.GalleryCars.Find(id);
            if (galleryCar == null)
            {
                return HttpNotFound();
            }
            return View(galleryCar);
        }
        

        // POST: GalleryCars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GalleryCar galleryCar = db.GalleryCars.Find(id);
            db.GalleryCars.Remove(galleryCar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC Blog</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="bnt-primary navbar navbar-default navbar-fixed-top"  >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Best Car Blog EVER", "Index", "Home", new { area = ""  }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" >
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Posts", "Index", "Posts")</li>
                    <li>@Html.ActionLink("Car Gallery", "Index", "GalleryCars")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Videos")</li>
                    <li>@Html.ActionLink("Contact Us", "Contacts", "Home")</li>
                    <li>@Html.ActionLink("Refereces","References","Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MVC Blog</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>